<html><head></head>
<body>
<style>
    
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
    }
    
    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }

</style>
<center>
    <div id="welcome">
        <center>
        <br />
        <h1>Welcome to the sample EvHttp Poll Application<h1 />
        <h3>using <span id="zf-name">Zend Framework</span><h3 /><br /><br />
        <div id="more-information">
			<br/>
            <A href="/login">Login Here</a>
        </div>
    </div>
</center>
</body>
</html>